### ISSUE TITLE
Default `Task` argument names to []

### ISSUE THREAD

**Issue by mattwynne** [cucumber-ltd/feynman#7]
This will avoid the noise when defining namespaces around tasks, like:

```javascript
const CreateProject = Task('CreateProject', [], Task => Task('named', ['projectName']))
```

and instead you can just write
```javascript
const CreateProject = Task('CreateProject', Task => Task('named', ['projectName']))
```

I know this is going to result in fiddly code that counts argument numbers but for readability of client code I think it's worth it.

**Comment by tooky** [comment]
What if the api was actually:

```
const CreateProject = Task('CreateProject', 'var', 'names' 'here', Task => Task('named', ['projectName']))
```

Then the underlying code can use `...names` and pop the last one if it's a function?

**Comment by mattwynne** [comment]
yeah, that could work too!
